### ISSUE TITLE
How to set redis brokers?

### ISSUE THREAD

**Issue by stavrosicsd** [electrical/puppet-beaver#22]
I dont see any way to set redis brokers via this module.
Redis is supposed to work with brokers to provide scalability, without this there is no reason to use redis. 

Can you please assist?

**Comment by electrical** [comment]
Hi,

There is a `beaver::output::redis` define to setup the redis output.
If you are meaning to setup Redis it self, best to use one of the many existing redis modules.

Cheers.

**Comment by stavrosicsd** [comment]
Ok I did not express my problem clearly.
I have 8 beaver clients and 4 redis brokers in my environment. How can I tell beaver clients (I have already studied the output code) to sent the logs to a list of brokers instead of only one redis host?

In your code I see $host as input which results in the beaver.conf:
redis_url = $host

In beaver.conf I should be able to set more than one redis_urls, which the module does not provide yet.

**Comment by electrical** [comment]
Ahh okay. sorry.  Looking at https://github.com/josegonzalez/python-beaver/blob/master/beaver/transports/redis_transport.py#L19 it seems you can have a list comma separated which should work.

**Comment by stavrosicsd** [comment]
Awsome. worked perfectly. I saw the code within the beaver::output::redis only.
Thank you very much.

**Comment by electrical** [comment]
no problem :-)

**Comment by stavrosicsd** [comment]
Ok the module does not support multi redis servers.
You assume only one redis server.
The correct syntax in beaver.conf for multiple redis servers would be:

redis_url: redis://redisA:6379/0, redis://redisB:6379/0

In the module if I set as host comma seperated redis servers I end up:
redis_url: redis://redisA,redisB:6379/0 

The reason is that in beaver::output::redis line #63 the beginning is hardcoded only for one server:
$opt_url = "redis_url: redis://${host}:${port}/${db}\n"

I think the fix is easy here, host should be replaced by hosts and loop over hosts to build the line with the correct syntax.

**Comment by electrical** [comment]
Ah okay, thanks for the heads up. I am planning to do a full rewrite of the module at some point, but the focus is with some other modules at this moment.. sorry
