### ISSUE TITLE
type fields do not need quotes

### ISSUE THREAD

**Issue by rtoma** [electrical/puppet-beaver#3]
Hi,

https://github.com/electrical/puppet-beaver/blob/master/manifests/input/file.pp#L54 contains:

```
$opt_type = "type: '${type}'\n"
```

These single-quotes become part of the value. I see them in redis and eventually in elasticsearch.

**Comment by electrical** [comment]
Oops okay. will change it.

**Comment by electrical** [comment]
The tags are still okay?

**Comment by rtoma** [comment]
I have not worked with tags yet, so I do not know.. Probably not?

**Comment by electrical** [comment]
Checked documentation and confirmed.
Fixed in 56ac0c2236103f593b5ef2750544f03a2099c822
