### ISSUE TITLE
beaver.conf file not being created

### ISSUE THREAD

**Issue by asaenz-vmware** [electrical/puppet-beaver#7]
In our Puppet module, we have some pretty basic lines:
class { 'beaver': }
    beaver::input::file{ 'testlog':
        file => '/etc/puppet/test.log',
        type => 'testlog'
     }
    beaver::output::redis{'redisout':
        host => '127.0.0.1'
    }

I am noticing, however, that there's no beaver.conf file in /etc/beaver/ (or any other file for that matter), which is causing beaver to fail to start up.  I don't see any kind of file being created in the puppet agent output either:
info: Applying configuration version '1371067499'
notice: /Stage[main]/Beaver::Package/Package[python-pip]/ensure: ensure changed 'purged' to 'present'
notice: /Stage[main]/Beaver::Package/Package[python-dev]/ensure: ensure changed 'purged' to 'present'
notice: /Stage[main]/Beaver::Package/Package[beaver]/ensure: created
notice: /Stage[main]/Beaver::Config/File[/etc/beaver/]/ensure: created
notice: /Stage[main]/Beaver::Service/File[/etc/init.d/beaver]/ensure: defined content as '{md5}52e9cfdf52b72322398ad362e2b8424f'
notice: /Stage[main]/Beaver::Service/Service[beaver]/ensure: ensure changed 'stopped' to 'running'
notice: Finished catalog run in 151.24 seconds

 Any idea what might be causing this?

**Comment by electrical** [comment]
Hmm strange. did you pick the latest code from git or a stable released version?

**Comment by asaenz-vmware** [comment]
I have the latest from git since the puppet forge module is out of date.

**Comment by asaenz-vmware** [comment]
GAH! I'm so sorry.  Turns out this was a case of me not knowing Puppet very well.  I had to edit the puppet.conf for pluginsync=true and it worked perfectly.  I hope I didn't waste much of your time on this...

**Comment by electrical** [comment]
Ahh no worries. It missed the library from the file_concat module then yeah.
Can happen :-)
